// app/layout.js
import { Geist, Geist_Mono, Outfit } from "next/font/google"; // Add Outfit here
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
    display:"swap" 
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
    display:"swap"
});

const outfit = Outfit({ 
  subsets: ["latin"], 
  weight: ["400","500","600","700"], 
  variable: "--font-outfit", // optional if you want to use CSS variable
  display:"swap"
});

export const metadata = {
  title: "Movwise",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={outfit.className}>
      <body>{children}</body>
    </html>
  );
}
